### ISSUE TITLE
Postgres user

### ISSUE THREAD

**Issue by opaque01** [alaub81/backup_docker_scripts#2]
Hallo

danke für das Script, allerdings bekomme ich einen Fehler und der dump ist leer.

```# ./backup-docker-postgres.sh 
Start 202112060549 Backup for Databases: 

 create Backup for Database on Container:
  * meine_db

/usr/lib/postgresql/9.5/bin/pg_dumpall: option requires an argument -- 'U'
Try "pg_dumpall --help" for more information.

202112060549 Backup for Databases completed
```

wenn ich in den User hardcoded in das Script schreibe klappt es:
```
docker exec $i pg_dumpall -c -U postgres | gzip > $BACKUPDIR/$i-$TIMESTAMP.sql.gz
```

LG opaque

**Comment by alaub81** [comment]
Hi!

sieht so aus als könnte er den Postgres User nicht auslesen. Schau mal was die Ausgabe von `env` im Postgres Container bringt. Da sollte der username auftauchen. Oder nutzt du ggf. Docker-Secrets? Dann geht das Script leider nicht.

Grüße
Andreas

**Comment by alaub81** [comment]
Hi @opaque01 ,

kann ich dir noch bei irgendwas helfen, oder kann das Ticket hier geschlossen werden?

Grüße
Andreas

**Comment by opaque01** [comment]
Danke, kann geschlossen werden.
