### ISSUE TITLE
Synology NAS

### ISSUE THREAD

**Issue by PeteSSMMSS** [alaub81/backup_docker_scripts#4]
does these scripts also work for docker in synology nas? I can´t find the path /usr/local/sbin there - so I tried to start a script from somewhere else but nothing happened

**Comment by alaub81** [comment]
I never tested that. The path, where you save the script is not important. You can put it where every you like. Under Linux a good path is `/usr/local/sbin`. 
Did you configure the script in a way, that it will use the right things on your synology nas?

**Comment by PeteSSMMSS** [comment]
I just changed the BACKUPDIR in backup-docker-volume.sh, and when I started the script with chmod +x (Synology path to the script) nothing happens in Terminal, and in the path are also no backup files. When I ssh to my Synology NAS all docker commands are working fine. I never start a .sh script before on my NAS, so maybe there is something else I need to change?

**Comment by alaub81** [comment]
which script are you using?

**Comment by PeteSSMMSS** [comment]
[backup-docker-volume.sh](https://github.com/alaub81/backup_docker_scripts/blob/main/backup-docker-volume.sh)

**Comment by alaub81** [comment]
did you configure the volumes you like to backup? Did you use `sudo`?

try this command: `docker volume ls -q`

I don not have the opportunity to test it by my own.
