### ISSUE TITLE
mariadb backup

### ISSUE THREAD

**Issue by bunkerman** [alaub81/backup_docker_scripts#5]
Hello,

I just used the script with the Linuxserver mariaDB container and got this error:
" create MYSQL Backup for Database on Container:
  *  DB on mariadb
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases
OR     mysqldump [OPTIONS] --system=[SYSTEMOPTIONS]]
For more options, use mysqldump --help"

I added --all-databases to the mysqldump within the script and then it works.

**Comment by bunkerman** [comment]
addidtion: I run the script in Open Media Vault. If I run it via CLI it works and if I run in  in the OMV GUI I get an "Error "The input device is not a TTY". I changed "docker exec -it" to "docker exec -i" and then it also works in the OMV GUI

**Comment by alaub81** [comment]
Hi @bunkerman ,

Thanks for the feedback. On my side the script did not work, too.

I changed the docker execution, the ```-ti``` is not necessary.

If you are using more than 1 database in a container, the script is not working. Adding the configuration switch ```--all-databases``` is a good way to solve this.

cheers
Andreas
