### ISSUE TITLE
Video wie man das benutzt ?

### ISSUE THREAD

**Issue by sk2eu** [alaub81/backup_docker_scripts#6]
HI 

Kannst du ein Vidoe machen wie man das hier benutzte am besten das https://www.laub-home.de/wiki/Docker_Backup_und_Restore_-_eine_kleine_Anleitung#Backup_via_Script

**Comment by alaub81** [comment]
Hi @sk2eu ,

nein sorry, das mache ich nicht. Wenn du Anleitungen auf Video Basis suchst, kannst du sicher etwas bei YouTube oder Konsorten finden.

cheers
Andreas
